ai_service: "custom"  # Options: "openai", "custom", "claude"
openai_api_key: 'your_openai_api_key'
openai_api_url: 'https://api.openai.com/v1/chat/completions'
openai_model: 'gpt-4-turbo'
custom_text_generation_api_url: 'http://127.0.0.1:5000/v1/chat/completions'
custom_text_generation_model: 'Llama-3-8B-Instruct-Coder-Q6_K'
claude_api_url: 'https://api.anthropic.com/v1/messages'
claude_api_key: 'your_claude_api_key'
claude_api_version: '2023-06-01'
claude_model: 'claude-3-sonnet-20240229'
target_language: 'Java'
max_tokens: 4096
prompt: 'Please convert the following C# code to Java. Here are the guidelines: 1. Preserve the original structure and logic of the code. 2. Convert C# syntax to the equivalent Java syntax. 3. Handle necessary imports or package statements. 4. Use appropriate Java equivalents for C#-specific libraries or functions. 5. Maintain proper indentation and code formatting. Please provide the converted Java code in your <response>, enclosed within <code> tags. If you have any additional thoughts or suggestions, include them within <thoughts> tags. Thank you!'
input_extension: '.cs'
output_extension: '.java'